"""initial schema

Revision ID: 50918319c659
Revises: 
Create Date: 2026-08-16 00:45:30.687930
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50918319c659'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('hourly', 'daily', 'weekly', name='frequency', native_enum=False, length=16), nullable=False),
    sa.Column('flavour', sa.Enum('learning', 'maintaining', name='flavour', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', name='subscriptionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('depth >= 1 AND depth <= 5', name='ck_subscription_depth'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_subscription_duration'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_next_due_at'), ['next_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('arc_summary', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('plan_prompt_version', sa.String(length=16), nullable=False),
    sa.Column('open_threads', sa.JSON(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('delivery',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('next_suggested', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('effort', sa.String(length=16), nullable=False),
    sa.Column('depth_rubric_version', sa.String(length=16), nullable=False),
    sa.Column('generation_prompt_version', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback', sa.Enum('too_basic', 'just_right', 'too_advanced', name='feedback', native_enum=False, length=16), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'issue_number', name='uq_delivery_issue')
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coverage_point',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('point', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_point_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coverage_point_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_point_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coverage_point_series_id'))

    op.drop_table('coverage_point')
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_series_id'))

    op.drop_table('delivery')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_tenant_id'))

    op.drop_table('series')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_next_due_at'))

    op.drop_table('subscription')
    # ### end Alembic commands ###
