"""coverage point compaction

Revision ID: 90b483e4ce44
Revises: 50918319c659
Create Date: 2026-08-16 10:49:57.078835
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90b483e4ce44'
down_revision: Union[str, None] = '50918319c659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.Enum('point', 'summary', name='coveragekind', native_enum=False, length=16), server_default='point', nullable=False))
        batch_op.add_column(sa.Column('compacted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage_point', schema=None) as batch_op:
        batch_op.drop_column('compacted_at')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
