"""delivery generation source

Revision ID: e82053c13046
Revises: 90b483e4ce44
Create Date: 2026-08-16 18:40:21.902245
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e82053c13046'
down_revision: Union[str, None] = '90b483e4ce44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('api', 'harness', name='generationsource', native_enum=False, length=16), server_default='api', nullable=False))
        batch_op.alter_column('model_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('effort',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.alter_column('effort',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('model_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('source')

    # ### end Alembic commands ###
