"""signal table

Revision ID: ef7b40c8752b
Revises: b7d41c9a2f10
Create Date: 2026-08-20 08:36:07.702426
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef7b40c8752b'
down_revision: Union[str, None] = 'b7d41c9a2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The evidence column is created nullable with no default and nothing
    # writes it — see CLAUDE.md's privacy section. It exists so the stance can
    # be inspected in the schema rather than taken on trust.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('signal_type', sa.Enum('asked_basic', 'asked_advanced', 'explained_to_ai', 'applied', 'struggled', 'delegated', 'topic_submission', name='signaltype', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidence', native_enum=False, length=16), nullable=False),
    sa.Column('context_category', sa.Enum('coding', 'troubleshooting', 'research', 'writing', 'meeting-prep', name='contextcategory', native_enum=False, length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('harness', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('extraction_prompt_version', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_signal_window', ['tenant_id', 'user_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_window')
        batch_op.drop_index(batch_op.f('ix_signal_user_id'))
        batch_op.drop_index(batch_op.f('ix_signal_tenant_id'))

    op.drop_table('signal')
    # ### end Alembic commands ###
